name: marketdata-stack

networks:
  marketdata_network:
    driver: bridge

volumes:
  redpanda-data:
  pgdata:

services:
  ###############################################################
  # 1. REDPANDA (Kafka broker)
  ###############################################################
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --pandaproxy-addr PLAINTEXT://0.0.0.0:8082
      - --advertise-pandaproxy-addr PLAINTEXT://redpanda:8082
      - --schema-registry-addr PLAINTEXT://0.0.0.0:8081
    ports:
      - "19092:19092"   # Kafka depuis Windows (C++ / Qt)
      - "9092:9092"     # Kafka inter-containers
      - "8081:8081"     # Schema Registry
      - "8082:8082"     # Pandaproxy
      - "9644:9644"     # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - marketdata_network

  ###############################################################
  # 2. REDPANDA CONSOLE (UI Kafka)
  ###############################################################
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.8.0
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    command: >
      /bin/sh -c
      'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml &&
       /app/console -config.filepath=/tmp/config.yml'
    networks:
      - marketdata_network

  ###############################################################
  # 3. POSTGRESQL
  ###############################################################
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - marketdata_network

  ###############################################################
  # 4. ADMINER (UI PostgreSQL)
  ###############################################################
  adminer:
    image: adminer:4
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "8090:8080"
    networks:
      - marketdata_network
